name: "backend_exporter"
version: "1.0.1"
settings:
  - name: "demo"
    model: "demo"
    interval: 1
    formatter: "Demo"
    metric: "Info"
  - name: "demo_gauge"
    model: "demo_gauge"
    interval: 1
    formatter: "DemoGauge"
    metric: "Gauge"
  - name: "test"
    model: "test"
    interval: 1
    formatter: "Test"
    metric: "Info"
