name: "backend_exporter"
version: "1.0.1"
settings:
  # - name: "demo"
  #   model: "demo"
  #   interval: 1
  #   formatter: "Demo"
  #   metric: "Info"
  - name: "service_status_gauge"
    model: "async_service"
    interval: 90
    formatter: "ServiceStatusModel"
    metric: "Gauge"
