Title: "Service status"
tasks:
  - name: "元大金控首頁"
    url: "https://www.yuanta.com/"
  - name: "元大證券"
    url: "https://www.yuanta.com.tw/eyuanta/"
  - name: "元大證券-線上開戶"
    url: "https://www.yuanta.com.tw/file-repository/content/accop/index.html?utm_source=officialwebsite&utm_medium=banner"
  - name: "元大證券-投資先生"
    url: "https://www.yuanta.com.tw/file-repository/content/mr_invest/index.html"
  - name: "元大證券-新戶優惠"
    url: "https://www.yuanta.com.tw/file-repository/content/deeppk/index.html"
  - name: "元大證券-台股定期定額"
    url: "https://www.yuanta.com.tw/file-repository/content/168easy/index.html"
  - name: "元大證券-美股定期定額"
    url: "https://www.yuanta.com.tw/file-repository/content/usadm/index.html"
  - name: "元大證券-FUND期金"
    url: "https://www.yuanta.com.tw/file-repository/content/fund2023/index.html"
  - name: "元大人壽"
    url: "https://www.yuantalife.com.tw/"
  - name: "元大人壽-繳費服務"
    url: "https://www.yuantalife.com.tw/our-services/insurance-policy/payment"
  - name: "元大人壽-借款服務"
    url: "https://www.yuantalife.com.tw/our-services/insurance-policy/loan"
  - name: "元大人壽-理賠服務"
    url: "https://www.yuantalife.com.tw/our-services/claim"
